import { translations, type Language } from './translations'

export function getDefaultStrings(lang: Language = 'BG') {
  const t = translations[lang]

  return {
    // Contact form
    contactForm: {
      namePlaceholder: t.contact.name,
      emailPlaceholder: t.contact.email,
      messagePlaceholder: t.contact.message,
      submitLabel: t.contact.send,
      submitLoadingLabel: `${t.common.loading}`,
      successHeading: t.contact.message_sent,
      successSubtext: t.contact.we_will_respond,
      successResetLabel: t.contact.send,
      errorText: t.errors.something_went_wrong,
      rateLimitedText: 'Твърде много опити. Опитай отново по-късно.',
      nameMinError: t.validation.field_required,
      emailInvalidError: t.validation.invalid_email,
      messageMinError: t.validation.field_required,
    },

    hero: {
      defaultHeadline: t.hero.default_headline,
      defaultSubtext: t.hero.default_subtext,
      viewAllDestinations: t.hero.view_all_destinations,
    },

    calendarCta: {
      heading: t.calendar_cta.heading,
      subheading: t.calendar_cta.subheading,
      button: t.calendar_cta.button,
    },

    a11y: {
      scrollLeft: t.a11y.scroll_left,
      scrollRight: t.a11y.scroll_right,
      close: t.a11y.close,
      previous: t.a11y.previous,
      next: t.a11y.next,
      copyLink: t.a11y.copy_link,
      keyboardShortcuts: t.a11y.keyboard_shortcuts,
      previousPhoto: t.a11y.previous_photo,
      nextPhoto: t.a11y.next_photo,
      navigationByDay: t.a11y.navigation_by_day,
      decrease: t.a11y.decrease,
      increase: t.a11y.increase,
      booking: t.a11y.booking,
      remove: t.a11y.remove,
      share: t.a11y.share,
    },

    destinations: {
      title: t.destinations.title,
      allDestinations: t.destinations.all_destinations,
      explore: t.destinations.explore,
      destinationDetails: t.destinations.destination_details,
    },

    // Newsletter form
    newsletterForm: {
      heading: t.footer.newsletter_heading,
      subheading: t.footer.newsletter_subtext,
      placeholder: t.newsletter.email_placeholder,
      buttonText: t.footer.submit_label,
      successMessage: t.common.success,
    },

    // Checkout
    checkout: {
      participationTypeLabel: t.checkout.participation_type,
      personalOption: t.checkout.personal,
      groupOption: t.checkout.group,
      corporateOption: t.checkout.corporate,
      selectParticipants: t.checkout.select_participants,
      firstName: t.auth.first_name,
      lastName: t.auth.last_name,
      email: t.auth.email,
      phone: t.auth.phone,
      dateOfBirth: t.checkout.date_of_birth,
      gender: t.checkout.gender,
      male: t.checkout.male,
      female: t.checkout.female,
      other: t.checkout.other,
      dietaryRestrictions: t.checkout.dietary_restrictions,
      emergencyContact: t.checkout.emergency_contact,
      specialRequests: t.checkout.special_requests,
      termsAndConditions: t.checkout.terms_and_conditions,
      iAgree: t.checkout.i_agree,
      placeOrder: t.checkout.place_order,
      paymentPending: t.checkout.payment_pending,
      success: t.checkout.success,
    },

    // Common
    common: {
      loading: t.common.loading,
      error: t.common.error,
      success: t.common.success,
      cancel: t.common.cancel,
      save: t.common.save,
      delete: t.common.delete,
      edit: t.common.edit,
      close: t.common.close,
      back: t.common.back,
      next: t.common.next,
      search: t.common.search,
      filter: t.common.filter,
      sort: t.common.sort,
      viewMore: t.common.view_more,
      readMore: t.common.read_more,
      noResults: t.common.no_results,
      from: t.common.from,
      to: t.common.to,
      date: t.common.date,
      time: t.common.time,
      price: t.common.price,
      duration: t.common.duration,
      difficulty: t.common.difficulty,
      distance: t.common.distance,
      guests: t.common.guests,
      available: t.common.available,
    },

    // Auth
    auth: {
      login: t.auth.login,
      signup: t.auth.signup,
      logout: t.auth.logout,
      password: t.auth.password,
      confirmPassword: t.auth.confirm_password,
      email: t.auth.email,
      firstName: t.auth.first_name,
      lastName: t.auth.last_name,
      phone: t.auth.phone,
      rememberMe: t.auth.remember_me,
      forgotPassword: t.auth.forgot_password,
      resetPassword: t.auth.reset_password,
      createAccount: t.auth.create_account,
      alreadyHaveAccount: t.auth.already_have_account,
      noAccount: t.auth.no_account,
      loginError: t.auth.login_error,
      signupError: t.auth.signup_error,
      signupSuccess: t.auth.signup_success,
      logoutSuccess: t.auth.logout_success,
    },

    // Trips
    trips: {
      title: t.trips.title,
      allTrips: t.trips.all_trips,
      featuredTrips: t.trips.featured_trips,
      upcoming: t.trips.upcoming,
      past: t.trips.past,
      bookNow: t.trips.book_now,
      details: t.trips.details,
      description: t.trips.description,
      itinerary: t.trips.itinerary,
      included: t.trips.included,
      notIncluded: t.trips.not_included,
      meetTime: t.trips.meet_time,
      startDate: t.trips.start_date,
      endDate: t.trips.end_date,
      maxParticipants: t.trips.max_participants,
      availableSpots: t.trips.available_spots,
      guide: t.trips.guide,
      equipment: t.trips.equipment,
      requirements: t.trips.requirements,
      weather: t.trips.weather,
      photos: t.trips.photos,
      reviews: t.trips.reviews,
      relatedTrips: t.trips.related_trips,
      priceFrom: t.trips.price_from,
      perPerson: t.trips.per_person,
    },

    // Shop
    shop: {
      title: t.shop.title,
      cart: t.shop.cart,
      checkout: t.shop.checkout,
      products: t.shop.products,
      price: t.shop.price,
      quantity: t.shop.quantity,
      addToCart: t.shop.add_to_cart,
      remove: t.shop.remove,
      update: t.shop.update,
      total: t.shop.total,
      subtotal: t.shop.subtotal,
      shipping: t.shop.shipping,
      tax: t.shop.tax,
      coupon: t.shop.coupon,
      couponCode: t.shop.coupon_code,
      applyCoupon: t.shop.apply_coupon,
      discount: t.shop.discount,
      continueShopping: t.shop.continue_shopping,
      proceedCheckout: t.shop.proceed_checkout,
      orderSummary: t.shop.order_summary,
      paymentMethod: t.shop.payment_method,
      billingAddress: t.shop.billing_address,
      shippingAddress: t.shop.shipping_address,
      orderConfirmation: t.shop.order_confirmation,
      orderNumber: t.shop.order_number,
      tracking: t.shop.tracking,
      inStock: t.shop.in_stock,
      outOfStock: t.shop.out_of_stock,
      emptyCart: t.shop.empty_cart,
    },

    // Calendar
    calendar: {
      title: t.calendar.title,
      allEvents: t.calendar.all_events,
      upcomingEvents: t.calendar.upcoming_events,
      pastEvents: t.calendar.past_events,
      event: t.calendar.event,
      date: t.calendar.date,
      time: t.calendar.time,
      location: t.calendar.location,
      viewEvent: t.calendar.view_event,
      register: t.calendar.register,
      registered: t.calendar.registered,
      registerNow: t.calendar.register_now,
      capacity: t.calendar.capacity,
      spotsLeft: t.calendar.spots_left,
    },

    // Footer
    footer: {
      company: t.footer.company,
      programs: t.footer.programs,
      aboutUs: t.footer.about_us,
      contacts: t.footer.contacts,
      blog: t.footer.blog,
      gallery: t.footer.gallery,
      community: t.footer.community,
      instagram: t.footer.instagram,
      facebook: t.footer.facebook,
      tiktok: t.footer.tiktok,
      upcomingTrips: t.footer.upcoming_trips,
      menu: t.footer.menu,
      rights: t.footer.rights,
      terms: t.footer.terms,
      privacy: t.footer.privacy,
    },

    // Validation
    validation: {
      fieldRequired: t.validation.field_required,
      invalidEmail: t.validation.invalid_email,
      invalidPhone: t.validation.invalid_phone,
      invalidUrl: t.validation.invalid_url,
      mustMatch: t.validation.must_match,
      onlyNumbers: t.validation.only_numbers,
      onlyLetters: t.validation.only_letters,
    },

    // Errors
    errors: {
      pageNotFound: t.errors.page_not_found,
      somethingWentWrong: t.errors.something_went_wrong,
      tryAgain: t.errors.try_again,
      backHome: t.errors.back_home,
      accessDenied: t.errors.access_denied,
      serverError: t.errors.server_error,
      notAuthorized: t.errors.not_authorized,
    },
  }
}
