import type { CollectionConfig } from 'payload'

export const EmailLogs: CollectionConfig = {
  slug: 'email-logs',
  admin: {
    group: 'Email Marketing',
    defaultColumns: ['recipient', 'subject', 'trigger', 'status', 'lastEventAt', 'sentAt'],
    description: 'Transactional, flow, and campaign email audit trail. Delivery events are verified webhooks from Resend.'
  },
  access: {
    read: ({ req }) => !!req.user,
    create: () => true,
    update: ({ req }) => !!req.user,
    delete: ({ req }) => !!req.user,
  },
  fields: [
    { name: 'flow', type: 'relationship', relationTo: 'email-flows', admin: { readOnly: true, description: 'Which EmailFlow triggered this send. Null for campaign sends.' } },
    { name: 'campaign', type: 'relationship', relationTo: 'campaigns', admin: { readOnly: true, description: 'Which Campaign triggered this send. Null for flow sends.' } },
    { name: 'trigger', type: 'text', admin: { readOnly: true } },
    { name: 'recipient', type: 'email', admin: { readOnly: true } },
    { name: 'subject', type: 'text', admin: { readOnly: true } },
    {
      name: 'status',
      type: 'select',
      options: [
        { label: 'Queued (delayed)', value: 'queued' },
        { label: 'Sent to Resend', value: 'sent' },
        { label: 'Delivered', value: 'delivered' },
        { label: 'Delivery delayed', value: 'delayed' },
        { label: 'Failed', value: 'failed' },
        { label: 'Suppressed', value: 'suppressed' },
        { label: 'Bounced', value: 'bounced' },
        { label: 'Spam complaint', value: 'complained' },
        { label: 'Opened', value: 'opened' },
        { label: 'Clicked', value: 'clicked' },
      ],
      defaultValue: 'sent',
      admin: { readOnly: true },
    },
    { name: 'scheduledFor', type: 'date', admin: { readOnly: true, description: 'Populated when status=queued.' } },
    { name: 'resendMessageId', type: 'text', admin: { readOnly: true } },
    { name: 'sentAt', type: 'date', admin: { readOnly: true } },
    { name: 'deliveredAt', type: 'date', admin: { readOnly: true } },
    { name: 'delayedAt', type: 'date', admin: { readOnly: true } },
    { name: 'failedAt', type: 'date', admin: { readOnly: true } },
    { name: 'suppressedAt', type: 'date', admin: { readOnly: true } },
    { name: 'openedAt', type: 'date', admin: { readOnly: true } },
    { name: 'bouncedAt', type: 'date', admin: { readOnly: true } },
    { name: 'complainedAt', type: 'date', admin: { readOnly: true } },
    { name: 'clickedAt', type: 'date', admin: { readOnly: true } },
    { name: 'lastEventType', type: 'text', admin: { readOnly: true, description: 'Latest event received from Resend.' } },
    { name: 'lastEventAt', type: 'date', admin: { readOnly: true, description: 'Timestamp supplied by Resend for the latest event.' } },
    { name: 'deliveryError', type: 'textarea', admin: { readOnly: true, description: 'Bounce, suppression, or provider failure reason.' } },
    { name: 'html', type: 'textarea', admin: { readOnly: true, description: 'Rendered email body snapshot when available.' } },
    { name: 'error', type: 'textarea', admin: { readOnly: true, description: 'Application send error.' } },
    { name: 'context', type: 'json', admin: { readOnly: true, description: 'Snapshot of all merge tag values at send time.' } },
  ],
}
