import type { CollectionConfig } from 'payload'

const TRIGGERS = [
  { label: 'Registration: Pending (request received)', value: 'registration_pending' },
  { label: 'Registration: Paid — Full Payment', value: 'registration_paid_full' },
  { label: 'Registration: Paid — Deposit', value: 'registration_paid_deposit' },
  { label: 'Registration: Confirmed by admin', value: 'registration_confirmed' },
  { label: 'Registration: Cancelled', value: 'registration_cancelled' },
  { label: 'Registration: Refunded', value: 'registration_refunded' },
  { label: 'Registration: Balance due in 7 days', value: 'registration_balance_due_7d' },
  { label: 'Registration: Balance due tomorrow', value: 'registration_balance_due_1d' },
  { label: 'Registration: Balance overdue', value: 'registration_balance_overdue' },
  { label: 'Registration: Balance charge failed (Stripe)', value: 'registration_balance_failed' },
  { label: 'Registration: Trip reminder 7 days before', value: 'registration_trip_reminder_7d' },
  { label: 'Registration: Trip reminder 1 day before', value: 'registration_trip_reminder_1d' },
  { label: 'Registration: Checked in (QR scanned)', value: 'registration_checkin' },
  { label: 'Registration: Certificate issued', value: 'registration_certificate' },
  { label: 'Registration: Post-trip review request', value: 'registration_review_request' },
  { label: 'Order: Paid — Full Payment', value: 'order_paid_full' },
  { label: 'Order: Paid — Deposit', value: 'order_paid_deposit' },
  { label: 'Order: Cancelled', value: 'order_cancelled' },
  { label: 'Order: Refunded', value: 'order_refunded' },
  { label: 'Order: Shipped (tracking set)', value: 'order_shipped' },
  { label: 'Order: Balance due in 7 days', value: 'order_balance_due_7d' },
  { label: 'Order: Balance due tomorrow', value: 'order_balance_due_1d' },
  { label: 'Order: Balance charge failed (Stripe)', value: 'order_balance_failed' },
  { label: 'Gift Voucher: Delivery to recipient', value: 'gift_voucher_recipient' },
  { label: 'Gift Voucher: Purchase confirmation to buyer', value: 'gift_voucher_buyer' },
  { label: 'Gift Voucher: Expiry reminder (7 days)', value: 'gift_voucher_expiry_7d' },
  { label: 'Subscription: Created / Welcome', value: 'subscription_created' },
  { label: 'Subscription: Payment failed (dunning 1)', value: 'subscription_payment_failed' },
  { label: 'Subscription: Payment failed (dunning 2)', value: 'subscription_dunning_2' },
  { label: 'Subscription: Payment failed (dunning 3 — final)', value: 'subscription_dunning_3' },
  { label: 'Subscription: Payment recovered', value: 'subscription_payment_recovered' },
  { label: 'Subscription: Cancelled', value: 'subscription_cancelled' },
  { label: 'Subscription: Renewal reminder (3 days)', value: 'subscription_renewal_3d' },
  { label: 'Loyalty: Tier upgraded', value: 'loyalty_tier_upgrade' },
  { label: 'Waitlist: Joined', value: 'waitlist_joined' },
  { label: 'Waitlist: Spot available', value: 'waitlist_spot_available' },
  { label: 'Waitlist: Offer expired', value: 'waitlist_expired' },
  { label: 'Stock Alert: Back in stock', value: 'stock_alert_notified' },
  { label: 'Abandoned Cart: 1 hour nudge', value: 'abandoned_cart_1h' },
  { label: 'Abandoned Cart: 24 hour nudge', value: 'abandoned_cart_24h' },
  { label: 'Auth: Password reset', value: 'auth_password_reset' },
  { label: 'Auth: Email verification', value: 'auth_email_verification' },
  { label: 'Custom (admin-defined key)', value: 'custom' },
]

export const EmailFlows: CollectionConfig = {
  slug: 'email-flows',
  admin: {
    group: 'Email Marketing',
    useAsTitle: 'label',
    defaultColumns: ['label', 'trigger', 'enabled', 'totalSent', 'lastTriggeredAt'],
  },
  fields: [
    {
      name: 'fireFlowAction',
      type: 'ui',
      admin: {
        position: 'sidebar',
        components: { Field: '@/payload/components/FireFlowButton#FireFlowButton' },
      },
    },
    { name: 'label', type: 'text', required: true, admin: { description: 'Human name shown in admin — e.g. "Booking Confirmed (Full Payment)"' } },
    { name: 'trigger', type: 'select', required: true, options: TRIGGERS },
    {
      name: 'customTriggerKey',
      type: 'text',
      admin: {
        condition: (data) => data.trigger === 'custom',
        description: 'Unique key for this custom flow. Fire it from code: sendFlow("custom:your_key_here", ...). Use snake_case.',
      },
    },
    { name: 'enabled', type: 'checkbox', defaultValue: false, admin: { description: 'Must be explicitly enabled after assigning a template. Disabling stops all sends for this trigger instantly.' } },
    { name: 'template', type: 'relationship', relationTo: 'email-templates', admin: { description: 'The email template to render and send.' } },
    { name: 'fromName', type: 'text', admin: { description: 'Override the global from name for this flow only.' } },
    { name: 'fromEmail', type: 'text', admin: { description: 'Override the global from email address.' } },
    { name: 'replyTo', type: 'text', admin: { description: 'Reply-to address for this flow.' } },
    { name: 'subjectOverride', type: 'text', admin: { description: 'Override the template subject. Supports merge tags.' } },
    { name: 'delayMinutes', type: 'number', defaultValue: 0, admin: { description: '0 = send immediately. E.g. 4320 = 3 days after trigger fires.' } },
    { name: 'ccAdmin', type: 'checkbox', defaultValue: false, admin: { description: 'BCC the admin email on every send from this flow.' } },
    { name: 'skipIfAlreadySent', type: 'checkbox', defaultValue: true, admin: { description: 'Do not send if an EmailLog already exists for this trigger + recipient.' } },
    {
      name: 'resendTags',
      type: 'array',
      fields: [
        { name: 'name', type: 'text', required: true },
        { name: 'value', type: 'text', required: true },
      ],
      admin: { description: 'Extra Resend tags attached to every email from this flow.' },
    },
    { name: 'featuredTrips', type: 'relationship', relationTo: 'trips', hasMany: true, admin: { description: 'Trips to include as {{featuredTrips}} array in this flow\'s emails.' } },
    { name: 'featuredPrograms', type: 'relationship', relationTo: 'programs', hasMany: true },
    { name: 'featuredDestinations', type: 'relationship', relationTo: 'destinations', hasMany: true },
    { name: 'notes', type: 'textarea', admin: { description: 'Internal admin notes about this flow.' } },
    { name: 'lastTriggeredAt', type: 'date', admin: { readOnly: true, position: 'sidebar', description: 'Last time this flow successfully fired.' } },
    { name: 'totalSent', type: 'number', defaultValue: 0, admin: { readOnly: true, position: 'sidebar', description: 'Total emails sent by this flow since creation.' } },
  ],
}
